/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statuscolors.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "fakefullscreenclient.h"
#include "focusdir.h"
#include "focusmaster.h"
#include "fullscreen.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "pertag.h"
#include "placedir.h"
#include "placemouse.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "selfrestart.h"
#ifdef XINERAMA
#include "sortscreens.h"
#endif // XINERAMA
#include "swallow.h"
#include "transfer.h"
#include "vanitygaps.h"
#include "zoomswap.h"
/* Layouts */
#include "layout_flextile-deluxe.h"
#include "layout_monocle.h"
#include "layout_tile.h"

