/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_ewmhtags.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statuscolors.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "dragcfact.c"
#include "fakefullscreenclient.c"
#include "focusdir.c"
#include "focusmaster.c"
#include "fullscreen.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "pertag.c"
#include "placedir.c"
#include "placemouse.c"
#include "restartsig.c"
#include "renamed_scratchpads.c"
#include "selfrestart.c"
#ifdef XINERAMA
#include "sortscreens.c"
#endif // XINERAMA
#include "swallow.c"
#include "transfer.c"
#include "vanitygaps.c"
#include "zoomswap.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_flextile-deluxe.c"
#include "layout_monocle.c"
#include "layout_tile.c"

